# Generated by Django 3.1.3 on 2021-01-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=80)),
                ('date', models.DateField(auto_now_add=True)),
                ('query', models.TextField()),
            ],
        ),
    ]
